version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack Gateway Port
      - "4572:4572" # S3 port (deprecated, use 4566 instead)
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./localstack:/var/lib/localstack"
    entrypoint: /bin/bash -c "docker-entrypoint.sh && ./init-s3.sh"
